# Development environment. This environment includes all the required
# packages for this repo including running the test suite.
name: srca
channels:
  - default
  - conda-forge
dependencies:
  - python=3.11.0
  - pymc
  - numba
  - pip
  - pip:
    - pyleoclim
